#!/usr/bin/sh
type apt-get > /dev/null && (
sudo apt-get update; sudo apt-get upgrade
sudo apt-get install --upgrade vim git zsh tmux
)
type git > /dev/null || exec echo "missing dependences: git not found"

[ -d $HOME/.oh-my-zsh ] || \
curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh

[ -d $HOME/.cfg ] || \
git clone --bare "https://github.com/ashuya/dotfiles.git" $HOME/.cfg

dotfiles="git --git-dir=$HOME/.cfg --work-tree=$HOME"

$dotfiles checkout > /dev/null || exec echo "checkout failed"

$dotfiles config --local status.showUntrackedFiles no

echo \
"everything set up \
Restart your shell to import it's config"
