#!/usr/bin/sh
type git > /dev/null || exec echo "missing dependences: git not found"

[ -d $HOME/.cfg ] || \
git clone --bare "https://github.com/ashuya/dotfiles.git" $HOME/.cfg

dotfiles="git --git-dir=$HOME/.cfg --work-tree=$HOME"

$dotfiles checkout > /dev/null || exec echo "checkout failed"

echo \
"dotfiles was successfully imported! \
Restart your shell to import it's config"
